Async
Meteor-Community-Packages/meteor-roles pull request #378
Opened 2023-08-24 09:51 UTC by StorytellerCZ

Continuation of #361

2023-08-24 10:12 UTC, StorytellerCZ commented
Now we mainly need to add test suite for async.

2023-08-24 11:16 UTC, jankapunkt requested changes
somehow we ended up with two meteor projects for testing, `someapp` and `testapp` and I think `someapp` has accidentally been added.

2023-08-24 11:16 UTC, jankapunkt commented on .DS_Store
I think we should remove .DS_Store files

2023-08-24 11:16 UTC, jankapunkt commented on someapp/packages/roles
is this a softlink file?

2023-08-25 07:33 UTC, StorytellerCZ commented on someapp/packages/roles
Removed someapp.

2023-08-25 07:33 UTC, StorytellerCZ commented on .DS_Store
Removed and added to `.gitignore`

2023-08-25 09:00 UTC, jankapunkt approved these changes

2023-09-24 10:24 UTC, StorytellerCZ commented
OK, figured out the tests, now it is just about converting the test suite to it.

2023-09-24 14:48 UTC, StorytellerCZ commented
Got all the async tests running.
I have removed migration tests which I don't feel need to be in the async tests as they should have been run before upgrading to Meteor 3, maybe we should mention that in the readme.

There seems to be a bug in the async version of detecting roles cycles in `_addRoleToParentAsync` function, which seem to break these tests. Right now I don't see what it could be as the async transition seems to have been done well. Fixing that I think could fix at least half the failing tests.

2023-09-24 16:28 UTC, bratelefant commented
> Got all the async tests running. I have removed migration tests which I don't feel need to be in the async tests as they should have been run before upgrading to Meteor 3, maybe we should mention that in the readme.
> 
> There seems to be a bug in the async version of detecting roles cycles in `_addRoleToParentAsync` function, which seem to break these tests. Right now I don't see what it could be as the async transition seems to have been done well. Fixing that I think could fix at least half the failing tests. @bratelefant any ideas?

Guess I fixed this, cf #380 

Sometimes it's the small things that matter ;)

2023-09-25 07:08 UTC, jankapunkt commented
Yup, tests are fixed, thanks @bratelefant 🙌

@StorytellerCZ from my end it's good, should we do a final review or do you think it's fine?

2023-09-25 07:39 UTC, StorytellerCZ commented
I think we might need client side tests for async as well, but I think it is fine. I will prepare a feature release once I get some time.

2023-10-14 10:28 UTC, StorytellerCZ commented
@jankapunkt so the client tests were much easier than I thought, honestly I kind of find them lacking, but that is for another time. For me we can merge and release this as a new feature version. I will have to look into re-generating the docs with this.

2023-10-14 10:31 UTC, jankapunkt approved these changes
Ltgm

2023-10-17 15:22 UTC, merged